version: '3.9'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_NO_SENTRY: true
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    volumes:
      - ./meilisearch-data:/meili_data
  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - ./redis-data:/data
